[package]
name = "recording-analyzer-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
derive_more = "0.99.0"
console_error_panic_hook = "*"
itertools = "0.10.0"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.4"

[lib]
crate-type = ["cdylib"]
